[package]
name = "websocket-pairing"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41", features = ["macros", "sync", "rt-multi-thread"] }
tokio-tungstenite = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3.31"
rand = "0.8"
